### ISSUE TITLE
getClustNum() error

### ISSUE THREAD

**Issue by WJaratlerdsiri-Lab** [xlucpu/MOVICS#10]
Hi,

I ran a problem with my copy number data in a position by sample matrix. Binary data of mutations are ok.

#Part of my copy number
[TAB]                          BRA08.T   BRA10.T   BRA13.T    BRA15.T KAL0004.T
1_108276812_108276812 -0.000720281 -0.454077 0.0047503 0.00339646  0.255127
1_108276813_108286811 -0.000720281 -0.454077 0.0047503 0.00339646  0.255127
1_108286812_108286812 -0.000720281 -0.454077 0.0047503 0.00339646  0.255127
1_108286813_108296810 -0.000720281 -0.454077 0.0047503 0.00339646  0.255127
1_108296811_108296811 -0.000720281 -0.454077 0.0047503 0.00339646  0.255127
1_108296812_108306810 -0.000720281 -0.454077 0.0047503 0.00339646  0.255127
[TAB]                       KAL0013.T KAL0022.T KAL0043.T  KAL0054.T KAL0072.T
1_108276812_108276812 -0.425851 0.0213336 -0.200039 0.00249974 -0.103276
1_108276813_108286811 -0.425851 0.0213336 -0.200039 0.00249974 -0.103276
1_108286812_108286812 -0.425851 0.0213336 -0.200039 0.00249974 -0.103276
1_108286813_108296810 -0.425851 0.0213336 -0.200039 0.00249974 -0.103276
1_108296811_108296811 -0.425851 0.0213336 -0.200039 0.00249974 -0.103276
1_108296812_108306810 -0.425851 0.0213336 -0.200039 0.00249974 -0.103276

#Command
Hrpcaall <- list(omics1 = Hrpcassm_mat,
                 omics2 = Hrpcacna_data )

optk.hrpca <- getClustNum(data        = Hrpcaall,
                         is.binary   = c(T,F), 
                         try.N.clust = 2:6,
                         fig.name    = "CLUSTER NUMBER")

# Error 
90% complete
95% complete
100% complete
calculating Gap-statistics...
Error in svd(B, nv = 0) : infinite or missing values in 'x'
Calls: getClustNum ... <Anonymous> -> msvd -> svd.sol -> nsmall.svd -> svd
Execution halted

I tried to transform data by adding +20 or round numbers to 3 digits. It still didn't work. I am not sure what causes the error. It seems not to be negative numbers. Or is it about column names? Your suggestion would be appreciated. I tried to debug myself for many days.

Thanks,
James

**Comment by xlucpu** [comment]
Really sorry for the delayed response.

It seems that your data cannot meet the requirement for one of the interatige clustering algorithm. I would suggest that you follow the vigneete and run each algorithm one by one to see which algoirthm causes such error, and start by then to check the data.

Best!

**Comment by Marchy-Lulu** [comment]
80% complete
85% complete
85% complete
90% complete
90% complete
95% complete
95% complete
100% complete
calculating Gap-statistics...
Error in crossprod(x$t) :"crossprod" is not a BUILTIN function.

According to the experience post website before, I tried to transform data round numbers to 3 digits. It still didn't work. I am not sure what causes the error.

Thanks，
Marchy

**Comment by YangLi20030521** [comment]
It means that you have columns composed of all zeroes or NA. Make sure clean your data. Here is my clean functions. 
clean_omics_data <- function(data_list) {
  cleaned_data <- lapply(data_list, function(df) {
    if (!is.null(attr(df, "na.action"))) {
      df <- df[-attr(df, "na.action"), ]
    }
    non_zero_cols <- rowSums(abs(df), na.rm = TRUE) > 0
    df <- df[non_zero_cols, , drop = FALSE]
    na_cols <- rowSums(is.na(df)) > 0
    df <- df[!na_cols, , drop = FALSE]
    return(df)
  })
  common_samples <- Reduce(intersect, lapply(cleaned_data, colnames))
  cleaned_data <- lapply(cleaned_data, function(df) df[, common_samples])
  return(cleaned_data)
}
mo.data_cleaned <- clean_omics_data(mo.data)
summary(mo.data_cleaned)
str(mo.data_cleaned$dat_mrna)
