### ISSUE TITLE
runPAM() error

### ISSUE THREAD

**Issue by tingszhang** [xlucpu/MOVICS#11]
yau.pam.pred <- runPAM(train.expr  = fpkm,
                       moic.res    = cmoic.brca,
                       test.expr   = brca.yau$mRNA.expr)
--all samples matched.
--a total of 8545 genes shared and used.
--log2 transformation done for training expression data.
--testing expression profile seems to have been standardised (z-score or log transformation), no more action will be performed.
Error in quantile.default(sd, offset.percent/100) : 
  'na.rm'如果设为FALSE的话不允许有遺漏值和NaN

I'm sure there's no NA.

**Comment by xlucpu** [comment]
I think it could be true that you have no NA in the expression data. However, it might have NaN after z-score normalization if you have genes with no expression at all or expressing in a constant value. I suggested that you picked up genes with high variability to do this analysis, or you remove those with constant value or no expression.
