### ISSUE TITLE
Have a question about how to select the algorithm

### ISSUE THREAD

**Issue by CQMUZC** [xlucpu/MOVICS#12]
R function "getConsensusMOIC" gets consensus from different algorithms, so I have a question about how to select the best combination. I know the silhouette is the evaluation indicator. But in my test, the combination having 0.9 silhouette does not have a survival difference. So if I wanna compare the difference and select the best, which functions I can perform, or whether you have a try.

**Comment by xlucpu** [comment]
The concept for MOVICS is to use as much as we have the integrative approach to perform a so-called multi-omics ensemble. There is no such function to investigate if there is any combination of approaches that enables getting back to you the "best" results. Therefore, I would suggest you use either one of the 10 algorithms that MOVICS provided (use the specific function directly), or use 10 algorithms and get the consensus results. If I would say, your subtype is so strong, it would not be totally shifted by a single outlier of the algorithm.

**Comment by CQMUZC** [comment]
Thanks for your valuable suggestion. But now, I am very interested in the evaluation of the combination. And it seems that different combination results in different subtype in my test. So maybe I would like to add the evaluation function based on your R package. I also wanna ask your opinion about the evaluation process, and whether the process is redundant or meaningless. If you wanna communicate with me in privacy, please don't hesitate to contact me and we can talk in wechar or twitter.
