### ISSUE TITLE
Error in compTMB()

### ISSUE THREAD

**Issue by mezarelab** [xlucpu/MOVICS#14]
Hi,
Thanks for your perfect package. I have problem in in compTMB() command. I have prepared my input data according to your sample file and instructions. But, it shows error:
#######################
--89 samples mismatched from current subtypes.
-Validating
--Removed 4190 duplicated variants
-Silent variants: 70969 
-Summarizing
--Possible FLAGS among top ten genes:
  TTN
  SYNE1
  MUC16
  OBSCN
-Processing clinical data
--Missing clinical data
-Finished in 2.840s elapsed (2.660s cpu) 
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique values when setting 'row.names': 
##############################

Then I deleted entire rows with "-" values in nucleotide columns (the last three columns). Then it shows this error:
#############################
--89 samples mismatched from current subtypes.
-Validating
--Removed 3712 duplicated variants
-Silent variants: 65787 
-Summarizing
--Possible FLAGS among top ten genes:
  TTN
  MUC16
  SYNE1
  OBSCN
-Processing clinical data
--Missing clinical data
-Finished in 2.840s elapsed (2.610s cpu) 
Error in `.rowNamesDF<-`(x, value = value) : 
  missing values in 'row.names' are not allowed
##############################

Then I deleted all nucleotide which were non SNP and finally it works. But, unfortunately the results was not reasonable (not significant  that I know it should be significant among 4 clusters). 

I will be thankful if you help me in this regard.

**Comment by xlucpu** [comment]
Sorry for the delayed response. Can you please check if your maf file could be correctly read by the read.maf() function in maftools R package? If so, compTMB should be okay to run, otherwise could you please check your file format again?
