### ISSUE TITLE
can not install dependency "CIMLR"

### ISSUE THREAD

**Issue by gzjtest** [xlucpu/MOVICS#15]
install.packages("~/R/x86_64-pc-linux-gnu-library/MOVICS-master.tar.gz", repos = NULL, type = "source")
将程序包安装入‘/home/guozhuangjie/R/x86_64-pc-linux-gnu-library/4.3’
(因为‘lib’没有被指定)
ERROR: dependency ‘CIMLR’ is not available for package ‘MOVICS’

> install.packages("/home/guozhuangjie/R/x86_64-pc-linux-gnu-library/CIMLR-1.0.0_R.tar.gz", repos = NULL, type = "source")
将程序包安装入‘/home/guozhuangjie/R/x86_64-pc-linux-gnu-library/4.3’
(因为‘lib’没有被指定)
* installing *source* package ‘CIMLR’ ...
** using staged installation
** libs
using C compiler: ‘gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
using C++ compiler: ‘g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG  -I'/home/guozhuangjie/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include'     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-DdVjkr/r-base-4.3.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG  -I'/home/guozhuangjie/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include'     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-DdVjkr/r-base-4.3.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c Rtsne.cpp -o Rtsne.o
gcc -I"/usr/share/R/include" -DNDEBUG  -I'/home/guozhuangjie/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include'     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-DdVjkr/r-base-4.3.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c projsplx_R.c -o projsplx_R.o
g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG  -I'/home/guozhuangjie/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include'     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-DdVjkr/r-base-4.3.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c sptree.cpp -o sptree.o
g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG  -I'/home/guozhuangjie/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include'     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-DdVjkr/r-base-4.3.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c tsne.cpp -o tsne.o
tsne.cpp: In member function ‘void TSNE::computeSquaredEuclideanDistance(double*, int, int, double*)’:
tsne.cpp:883:11: error: too few arguments to function ‘void dgemm_(const char*, const char*, const int*, const int*, const int*, const double*, const double*, const int*, const double*, const int*, const double*, double*, const int*, size_t, size_t)’
  883 |     dgemm_("T", "N", &N, &N, &D, &a1, X, &D, X, &D, &a2, DD, &N);
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/share/R/include/R.h:78,
                 from /home/guozhuangjie/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include/Rcpp/r/headers.h:66,
                 from /home/guozhuangjie/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include/RcppCommon.h:30,
                 from /home/guozhuangjie/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include/Rcpp.h:27,
                 from tsne.cpp:39:
/usr/share/R/include/R_ext/BLAS.h:207:10: note: declared here
  207 | F77_NAME(dgemm)(const char *transa, const char *transb, const int *m,
      |          ^~~~~
/usr/share/R/include/R_ext/RS.h:77:25: note: in definition of macro ‘F77_CALL’
   77 | # define F77_CALL(x)    x ## _
      |                         ^
/usr/share/R/include/R_ext/BLAS.h:207:1: note: in expansion of macro ‘F77_NAME’
  207 | F77_NAME(dgemm)(const char *transa, const char *transb, const int *m,
      | ^~~~~~~~
tsne.cpp: In member function ‘bool TSNE::load_data(double**, int*, int*, int*, double*, double*, int*)’:
tsne.cpp:938:14: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  938 |         fread(n, sizeof(int), 1, h);                                                                                    // number of datapoints
      |         ~~~~~^~~~~~~~~~~~~~~~~~~~~~
tsne.cpp:939:14: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  939 |         fread(d, sizeof(int), 1, h);                                                                                    // original dimensionality
      |         ~~~~~^~~~~~~~~~~~~~~~~~~~~~
tsne.cpp:940:10: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  940 |     fread(theta, sizeof(double), 1, h);                                                                         // gradient accuracy
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tsne.cpp:941:14: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  941 |         fread(perplexity, sizeof(double), 1, h);                                                                // perplexity
      |         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tsne.cpp:942:8: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  942 |   fread(no_dims, sizeof(int), 1, h);                                      // output dimensionality
      |   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
tsne.cpp:945:10: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  945 |     fread(*data, sizeof(double), *n * *d, h);                               // the data
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tsne.cpp:946:27: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  946 |         if(!feof(h)) fread(rand_seed, sizeof(int), 1, h);                       // random seed
      |                      ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [/usr/lib/R/etc/Makeconf:200：tsne.o] 错误 1
ERROR: compilation failed for package ‘CIMLR’

that is all .who can help me plz. thank you

**Comment by xlucpu** [comment]
Can you please follow the Troubleshooting part detailed in the README? Depends on your operating system I provided the solutions at least when I was testing the installation.
