### ISSUE TITLE
how to prepare test data？

### ISSUE THREAD

**Issue by wslj1993** [xlucpu/MOVICS#16]
hello，could you provide some docunments to prepare the data，which includes rna，cnv，metabolites data and so on？

**Comment by xlucpu** [comment]
Hi, in the data demo you have see clear the structure of data in put, it is basically dataframe for each omics data type with different rows (features) but exactly the same columns (samples). I think it would be beneficial if you can follow the vignette to understand the input.

**Comment by wslj1993** [comment]
thanks

**Comment by wslj1993** [comment]
by the way,this tools can be used to analysis data from 3 sources（metabolome, lipidome and microbiome）？

**Comment by xlucpu** [comment]
Hi, technically it does not matter what sources you used. MOVICS can run perfectly if you feed it with correct data format (less than six 'omics' data type).

**Comment by wslj1993** [comment]
ok，thanks

**Comment by wslj1993** [comment]
hello，data should be normalized ？i try to scale the data ,which is the way to deal with. this is right?

**Comment by wslj1993** [comment]
> Hi, technically it does not matter what sources you used. MOVICS can run perfectly if you feed it with correct data format (less than six 'omics' data type).
