### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by zenglongjin** [xlucpu/MOVICS#8]
The windows exhibited:
Warning in .recacheSubclasses(def@className, def, env) :
  undefined subclass "numericVector" of class "Mnumeric"; definition not updated
错误: 'namespace:ggpmisc'没有出口'geom_table'这个对象
停止执行
The same error occurred after a successful installation.

**Comment by xlucpu** [comment]
Please use older version of ggpmisc such as 0.3.6. I will fix this bug shortly.

**Comment by zenglongjin** [comment]
Thank you very much ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月18日(星期天) 下午2:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xlucpu/MOVICS] Installation failed (#8)
